# -*- coding: utf-8 -*-
"""goods_online.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oc5TFlJIBKm3wriMDPZw2EXRT4a3bfHY
"""

def add_goods(name):
  print('재고 추가 : ' + name)