# -*- coding: utf-8 -*-
"""헤이파이썬 8 모듈과 패키지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYEHAFGAM81wj1zq8QXweKwh3X9aQl0s

#8-1 모듈
"""

def user_age(year):
  return 2024-year

def user_gender(minnum):
  if int(minnum[7])%2==0:
    return '여성'
  else:
    return '남성'

